name: flooperman
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  html: ^0.15.0
  file_picker: ^5.3.1
  path_provider: ^2.0.15
  just_audio: ^0.9.34
  get: ^4.6.5
  sticky_footer_scrollview: ^1.1.1
  easy_search_bar: ^2.5.0
  get_storage: ^2.1.1
  flutter_download_manager: ^0.5.5
  dart_tags: ^0.4.0
  flutter_native_drag_n_drop: ^1.2.4
  super_drag_and_drop: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
