name: flooperman
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  html: ^0.15.0
  file_picker: ^5.3.1
  path_provider: ^2.0.15
  just_audio: ^0.9.34
  get: ^4.6.5
  sticky_footer_scrollview: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
